version: 0.2
env:
  variables:
    AWS_REGION: "ap-south-1"
    DOCKER_REGISTRY: "public.ecr.aws/q4m2j8z0"
    TOKEN: "eyJwYXlsb2FkIjoiRW0wOEw4aTBmRTNtRi90akpyQW5nRDdHK0Vjc2IyQ21SbldaeCtYS0REWGtTZlNXVHFuM0g2bDRYKytNdnFOamk3b3o0UmxlOWJNUzNhME1rQ09ZdW9XUzRrZ1hOUmhGelZoMWQxb1dLdHZNS1B1ek44Q2p2ZmRvaTNoN2ZmYzJNMXk5bXYxSEl3ZlN0LzNuenhWcUt3RExjWG01dlROcVBkWVpXWHFQU2NIeDliRnViMkI0cHBLMWkzcCszK2RObkJCMCt1OW0zYzRoaVVIWEtxTldGT0k5d0hOTGtsUW4ybmdQTE1vR283UytuMXlKMnAzcWd0dXBsZkQ2ZFMzbVVTalVEU0xYZzBXeVpiZ25wcUF2aGg5NUhWZWJUTlE3UTBXU1QxbHN0T1pTMlA5aWg3YjRsRDRBcHNVZXdpeVVmV1R3ZFRRc3d5QXlER2Q4VDZXMXUxMncrdVhBZE9IRzBIMU0rS2RLOEdJRytQeEl1bmIwcjJxME51R0c4d0liS1N4VVljOXh1aDAxQUZNaHZITmtSVENGVmFndXZLODd2eklCcm5pTkZtVlA2cWYwZXFibUhOenBBM1cyR2UwbG5kbHJJZzYyY1Y0bEpwVUo4VDQzTnBRS0lMWHEraWpNTEt1aVFMc0tpRlVrY29rMWh4TWJTVC8xSy9LRFJFcjhFNEJzbTJ5dTA2d3dieFI3ZWN3bkRWN2hCc0twVFpxYno0VjZaVHpCRkZTZU5WdUlOdzE2WWwxa25uQThhbUQyWnAzL3ltcitCT0lhOXlvOW9mY1RXQlBLVTQxaG81cVp1b1ZDWVJnajlsdkY2N1docm01SENqQ1FIb0I5TW9tbTlQSzFDMlJVTEFZeE1GLzdFQng2L1I0Um01VXhGSE1yM1RLSi9RVXNtMWdoMmIzRVZqc1JBK1hnVmNucFNuVmRFWmY1bnZUTTk3V29oOHRkV21QR2xqQXBNMXFtSUVab25ZVHJxZ05Hb0t5b28xTDB0VkNoRWg3TnZLdXFXWitweWlmQytoVVR4Q2lLSWYrUEFFdDkzeTFxNnAvUEZWNlR4WitMWDRuOHVBTTFiVUNXTWpRODBaT1ozWGszVmNqUHNMZXduQTZiTlhQVFFmT3hFT0xLdzVPT1RONFBwbUp2T1dCMWVINlU3UEtkKzRPUm9BYlp4N0NZNVdrNDdORExRaTRGc3pKa3lQNnc4S293ZmtuanBNM3FvTTNENDJwV21mRnBkR2hCQ3dCZmxEMEFjd3d4QzNvU21xVDlUejNkRWFrSDJha25YZEptOUU1Z2ZBaHcwR0V2UHEvQnVNTjg0eTdQcDJFaFNHQ1lNN2JOaGY2NVNEalYwRUozb3lUNUk4ZVQ0Rkp6RVlJVmxjaGtUcjk0cTZHd3hrYkZSSFZCVmdRWWhQWT0iLCJkYXRha2V5IjoiQVFJQkFIaUhXYVlUblJVV0NibnorN0x2TUcrQVB2VEh6SGxCVVE5RnFFbVYyNkJkd3dFQWZKcklYSDZrVElldVBxMFFtVk1ZQUFBQWZqQjhCZ2txaGtpRzl3MEJCd2FnYnpCdEFnRUFNR2dHQ1NxR1NJYjNEUUVIQVRBZUJnbGdoa2dCWlFNRUFTNHdFUVFNdDVoY2RYdTc0S3N5MWNkb0FnRVFnRHRuV0lja3lKT3hEVW1WWnRlOHQ4RzNYYzd6Q1U5SkN4RzZsdk1tTzBtWUc0dmljNEVMU2VXRXJaeHVUVmtieHBLbTErTlhIaFd0SCtIYUxnPT0iLCJ2ZXJzaW9uIjoiMiIsInR5cGUiOiJEQVRBX0tFWSIsImV4cGlyYXRpb24iOjE2NjIwODI3Nzh9"

phases:
  pre_build:
    commands:
      - echo prebuild
      # - export password=$(aws ecr get-login-password --region $AWS_REGION)
      # - echo $password
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q4m2j8z0
      # - docker login -u AWS -p $TOKEN $DOCKER_REGISTRY
  build:
    commands:
      - echo build
  post_build:
    commands:
      - echo postbuild
artifacts:
  files:
   - target/app.jar