version: 0.2


phases:
  pre_build:
    commands:
      - echo prebuild
  build:
    commands:
      - echo build
  post_build:
    commands:
      - echo postbuild
artifacts:
  files:
   - target/app.jar