version: 0.2
env:
  variables:
    AWS_REGION: "ap-south-1"

phases:
  pre_build:
    commands:
      - echo prebuild
      - export password=$(aws ecr get-login-password --region $AWS_REGION)
      - echo $password
  build:
    commands:
      - echo build
  post_build:
    commands:
      - echo postbuild
artifacts:
  files:
   - target/app.jar